# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := msm8930
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := msm8930
TARGET_BOARD_PLATFORM_GPU := qcom-adreno305

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := krait

# Kernel
BOARD_KERNEL_BASE := 80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 00008000
BOARD_RAMDISK_OFFSET := 02000000
BOARD_SECOND_OFFSET := 00f00000
BOARD_TAGS_OFFSET := 00000100
BOARD_HASH_TYPE := sha1
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 maxcpus=2
# BOARD_MKBOOTIMG_ARGS := --kernel_offset 00008000 --ramdisk_offset 02000000 --second_offset 00f00000 --hash sha1
TARGET_PREBUILT_KERNEL := device/huawei/ascendg740/kernel/zImage
 



# Partition info
TARGET_USERIMAGES_USE_EXT4 := true
# TARGET_PLATFORM_DEVICE_BASE :=
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
# BOARD_FLASH_BLOCK_SIZE := 
BOARD_FLASH_BLOCK_SIZE := 131072 # Probabily wrong

# TWRP
#TW_THEME := portrait_hdpi
TW_TARGET_USES_QCOM_BSP := true

RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_USB_STORAGE := true

HAVE_SELINUX := false
DEVICE_RESOLUTION := 720x1280
BOARD_HAS_NO_REAL_SDCARD := false 
TW_INTERNAL_STORAGE_PATH  := "/HWUserData"
TW_INTERNAL_STORAGE_MOUNT_POINT := "internal_sd" 
TW_EXTERNAL_STORAGE_PATH := "/external_sd" 
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd" 

